# Generated by Django 4.1.7 on 2023-03-18 19:36

from django.db import migrations, models
import my_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=my_site.models.upload_to, verbose_name='Image'),
        ),
    ]
