# Generated by Django 4.1.7 on 2023-03-19 08:44

from django.db import migrations, models
import my_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/no_image.png', upload_to=my_site.models.upload_to, verbose_name='Image'),
        ),
    ]
